// Regional sampling network — compiled from eDNA_sampling_sites_2026 - eDNA Sites.csv
// Static snapshot (not live-fetched). Re-export and hand off a new CSV to refresh.
const NETWORK_SITES = [
  {
    "name": "Pillar Point",
    "siteCode": "CAS-PIPO",
    "region": "CenCal",
    "group": "CAS",
    "lead": "Johnson Carver",
    "lat": 37.494667,
    "lng": -122.49875,
    "date": "",
    "status": "sampled",
    "season": "June 2026",
    "purpose": "Snapshot Cal Coast and Soltice Sea Star Search",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "6",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Fitzgerald Marine Reserve-Seal Cove",
    "siteCode": "CAS-SECO",
    "region": "CenCal",
    "group": "CAS",
    "lead": "Johnson Carver",
    "lat": 37.519166,
    "lng": -122.514121,
    "date": "",
    "status": "sampled",
    "season": "June 2026",
    "purpose": "Snapshot Cal Coast and Soltice Sea Star Search",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "6",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Pescadero Point",
    "siteCode": "CAS-PEPO",
    "region": "CenCal",
    "group": "CAS",
    "lead": "Johnson Carver",
    "lat": 37.246553,
    "lng": -122.419789,
    "date": "",
    "status": "sampled",
    "season": "June 2026",
    "purpose": "Snapshot Cal Coast and Soltice Sea Star Search",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "6",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Pistachios",
    "siteCode": "CAS-PIST",
    "region": "CenCal",
    "group": "CAS",
    "lead": "Johnson Carver",
    "lat": 37.19299,
    "lng": -122.401813,
    "date": "",
    "status": "sampled",
    "season": "June 2026",
    "purpose": "Snapshot Cal Coast and Soltice Sea Star Search",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "6",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Baker Beach",
    "siteCode": "CAS-BABE",
    "region": "NorCal",
    "group": "CAS",
    "lead": "Johnson Carver",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "sampled",
    "season": "June 2026",
    "purpose": "Snapshot Cal Coast and Soltice Sea Star Search",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "6",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Samoa Boat Launch",
    "siteCode": "CAS-SABO",
    "region": "NorCal",
    "group": "CAS",
    "lead": "Johnson Carver",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "sampled",
    "season": "June 2026",
    "purpose": "Snapshot Cal Coast and Soltice Sea Star Search",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "6",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "King Salmon",
    "siteCode": "CAS-KISA",
    "region": "NorCal",
    "group": "CAS",
    "lead": "Johnson Carver",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "sampled",
    "season": "June 2026",
    "purpose": "Snapshot Cal Coast and Soltice Sea Star Search",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "6",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Luffenholtz",
    "siteCode": "CAS-LUFF",
    "region": "NorCal",
    "group": "CAS",
    "lead": "Johnson Carver",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "sampled",
    "season": "June 2026",
    "purpose": "Snapshot Cal Coast and Soltice Sea Star Search",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "6",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Van Damme State Beach",
    "siteCode": "CAS-VADA",
    "region": "NorCal",
    "group": "CAS",
    "lead": "Johnson Carver",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "sampled",
    "season": "June 2026",
    "purpose": "Snapshot Cal Coast and Soltice Sea Star Search",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "6",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Moat Creek",
    "siteCode": "CAS-MACR",
    "region": "NorCal",
    "group": "CAS",
    "lead": "Johnson Carver",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "sampled",
    "season": "June 2026",
    "purpose": "Snapshot Cal Coast and Soltice Sea Star Search",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "6",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Sonoma County (tbd)",
    "siteCode": "",
    "region": "NorCal",
    "group": "CAS",
    "lead": "Johnson Upton Carver",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "planned",
    "season": "Late Summer or Fall 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Point Cavallo",
    "siteCode": "PTCAVA",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 37.8332,
    "lng": -122.469237,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Pedro Point",
    "siteCode": "PEDRPT",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 37.594214,
    "lng": -122.523369,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Beach Street",
    "siteCode": "BCHSTR",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 37.5244,
    "lng": -122.5258,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Half Moon Reef",
    "siteCode": "HFMNRF",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 37.486328,
    "lng": -122.49044,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Pigeon Point",
    "siteCode": "PIGEON",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 37.181929,
    "lng": -122.39156,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Ano Nuevo",
    "siteCode": "ANEUVO",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 37.110731,
    "lng": -122.320222,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Sandhill",
    "siteCode": "SANDHL",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 36.97293,
    "lng": -122.149429,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Andrew Molera",
    "siteCode": "ANDMOL",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 36.277685,
    "lng": -121.875988,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "La Cruz",
    "siteCode": "LACRUZ",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 35.713009,
    "lng": -121.325389,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "San Simeon",
    "siteCode": "SIMEON",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 35.630567,
    "lng": -121.19494,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Cambria",
    "siteCode": "CMBRIA",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 35.570495,
    "lng": -121.127145,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "White Rock",
    "siteCode": "WHTRCK",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 35.5271,
    "lng": -121.089899,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Cayucos",
    "siteCode": "CAYUCO",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 35.434393,
    "lng": -120.947256,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Little Irish",
    "siteCode": "IRISH",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 35.175931,
    "lng": -120.812501,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Point Sal",
    "siteCode": "PNTSAL",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 34.871733,
    "lng": -120.630083,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Purisima",
    "siteCode": "PURSIM",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 34.726948,
    "lng": -120.627138,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Arroyo Quemado",
    "siteCode": "QUEMDO",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 34.46835,
    "lng": -120.125183,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Cojo",
    "siteCode": "COJOBY",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 34.443204,
    "lng": -120.423326,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Naples Reef",
    "siteCode": "NAPLES",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 34.42185,
    "lng": -119.9515,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "IV Reef",
    "siteCode": "IVREEF",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem Kidd Pacheco",
    "lat": 34.404733,
    "lng": -119.876283,
    "date": "",
    "status": "sampled",
    "season": "Winter 2026 & ongoing?",
    "purpose": "Water for eDNA and Vpec. Pair with dive surveys",
    "ednaBenthic": "5",
    "ednaSurface": "5",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Matterhorn",
    "siteCode": "",
    "region": "SoCal",
    "group": "Galaxy Quest",
    "lead": "Kidd",
    "lat": 33.72916,
    "lng": -119.161,
    "date": "",
    "status": "sampled",
    "season": "",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Moat Creek",
    "siteCode": "MOATCK",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 38.882439,
    "lng": -123.673657,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "8",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Serenisea",
    "siteCode": "SRNSEA",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 38.798248,
    "lng": -123.57116,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "8",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Sculpture Point",
    "siteCode": "SCLPPT",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 38.701552,
    "lng": -123.444217,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "8",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Twin Coves",
    "siteCode": "TCOVES",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 38.461845,
    "lng": -123.146071,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "8",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Bodega Harbor",
    "siteCode": "BODHBR",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 38.333263,
    "lng": -123.052314,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "8",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Duxbury Reef",
    "siteCode": "DBREEF",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 37.889923,
    "lng": -122.707059,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "8",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Arena Cove",
    "siteCode": "ARCOVE",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 38.91402,
    "lng": -123.70979,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "8",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "Point Arena Pier",
    "vpecOnly": false
  },
  {
    "name": "Pudding Creek",
    "siteCode": "",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 39.46086,
    "lng": -123.8093,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "4",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Manchester SP",
    "siteCode": "",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 38.9829601,
    "lng": -123.7054673,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "4",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Navarro Beach",
    "siteCode": "",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 39.18743,
    "lng": -123.75728,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "4",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Van Damme SP",
    "siteCode": "",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 39.27171,
    "lng": -123.79077,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "4",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Mendocino Headlands",
    "siteCode": "",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 39.30792,
    "lng": -123.81043,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "4",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Caspar Beach",
    "siteCode": "",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 39.31672,
    "lng": -123.81673,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "4",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Jug Handle Beach",
    "siteCode": "",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 39.37666,
    "lng": -123.81796,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "4",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Noyo Beach",
    "siteCode": "",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 39.42811,
    "lng": -123.80939,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "3",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Shell Beach",
    "siteCode": "",
    "region": "NorCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 38.72505,
    "lng": -123.48064,
    "date": "",
    "status": "sampled",
    "season": "January 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "5",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Harris Point West",
    "siteCode": "HARRIS",
    "region": "SoCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 34.0637,
    "lng": -120.356,
    "date": "",
    "status": "sampled",
    "season": "September 2025",
    "purpose": "",
    "ednaBenthic": "9",
    "ednaSurface": "1",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Cuyler West",
    "siteCode": "CUYLER",
    "region": "SoCal",
    "group": "Galaxy Quest",
    "lead": "Pacheco",
    "lat": 34.0571,
    "lng": -120.3526,
    "date": "",
    "status": "sampled",
    "season": "September 2025",
    "purpose": "",
    "ednaBenthic": "9",
    "ednaSurface": "1",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "Frozen",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "East Sound",
    "siteCode": "",
    "region": "WA",
    "group": "Gold",
    "lead": "Gold",
    "lat": 48.674958,
    "lng": -122.898606,
    "date": "",
    "status": "",
    "season": "Summer 2026",
    "purpose": "Paired 6 gill + Pycno surveys for comparing detections and seasonal variability",
    "ednaBenthic": "Benthic",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "Exact sites/GPS TBD, paired with 6 gill eDNA + diver surveys",
    "vpecOnly": false
  },
  {
    "name": "West Sound",
    "siteCode": "",
    "region": "WA",
    "group": "Gold",
    "lead": "Gold",
    "lat": 48.628235,
    "lng": -122.977227,
    "date": "",
    "status": "",
    "season": "Summer 2026",
    "purpose": "Paired 6 gill + Pycno surveys for comparing detections and seasonal variability",
    "ednaBenthic": "Benthic",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "Exact sites/GPS TBD, paired with 6 gill eDNA + diver surveys",
    "vpecOnly": false
  },
  {
    "name": "Lime Kiln",
    "siteCode": "",
    "region": "WA",
    "group": "Gold",
    "lead": "Gold",
    "lat": 48.515559,
    "lng": -123.155412,
    "date": "",
    "status": "",
    "season": "Summer 2026",
    "purpose": "Paired 6 gill + Pycno surveys for comparing detections and seasonal variability",
    "ednaBenthic": "Benthic",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "Exact sites/GPS TBD, paired with 6 gill eDNA + diver surveys",
    "vpecOnly": false
  },
  {
    "name": "Eagle Cove",
    "siteCode": "",
    "region": "WA",
    "group": "Gold",
    "lead": "Gold",
    "lat": 48.481434,
    "lng": -123.091897,
    "date": "",
    "status": "",
    "season": "Summer 2026",
    "purpose": "Paired 6 gill + Pycno surveys for comparing detections and seasonal variability",
    "ednaBenthic": "Benthic",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "Exact sites/GPS TBD, paired with 6 gill eDNA + diver surveys",
    "vpecOnly": false
  },
  {
    "name": "Seattle Aquarium",
    "siteCode": "",
    "region": "WA",
    "group": "Gold",
    "lead": "Gold",
    "lat": 47.607125,
    "lng": -122.342398,
    "date": "",
    "status": "",
    "season": "Summer 2026",
    "purpose": "Paired 6 gill + Pycno surveys for comparing detections and seasonal variability",
    "ednaBenthic": "Benthic",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "Exact sites/GPS TBD, paired with 6 gill eDNA + diver surveys",
    "vpecOnly": false
  },
  {
    "name": "Redondo",
    "siteCode": "",
    "region": "WA",
    "group": "Gold",
    "lead": "Gold",
    "lat": 47.349392,
    "lng": -122.32646,
    "date": "",
    "status": "",
    "season": "Summer 2026",
    "purpose": "Paired 6 gill + Pycno surveys for comparing detections and seasonal variability",
    "ednaBenthic": "Benthic",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "1L gravity",
    "storage": "100% ethanol + frozen",
    "notes": "Exact sites/GPS TBD, paired with 6 gill eDNA + diver surveys",
    "vpecOnly": false
  },
  {
    "name": "Burke",
    "siteCode": "",
    "region": "BC",
    "group": "Hakai",
    "lead": "Gehman",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "",
    "season": "May, September 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Rivers Inlet",
    "siteCode": "",
    "region": "BC",
    "group": "Hakai",
    "lead": "Gehman",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "",
    "season": "May, September 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Choked Pass",
    "siteCode": "",
    "region": "BC",
    "group": "Hakai",
    "lead": "Gehman",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "",
    "season": "May, September 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Kwakshua Channel",
    "siteCode": "",
    "region": "BC",
    "group": "Hakai",
    "lead": "Gehman",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "",
    "season": "May, September 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Meay Channel",
    "siteCode": "",
    "region": "BC",
    "group": "Hakai",
    "lead": "Gehman",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "",
    "season": "May, September 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Mustang",
    "siteCode": "",
    "region": "BC",
    "group": "Hakai",
    "lead": "Gehman",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "",
    "season": "May, September 2026",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "The Hellbow",
    "siteCode": "HELBOW",
    "region": "Oregon",
    "group": "PORKA",
    "lead": "Gravem",
    "lat": 42.733528,
    "lng": -124.509416,
    "date": "",
    "status": "Planned",
    "season": "Summer 2026, weekly Aug- Sept",
    "purpose": "Pycnopodia additions",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Arena Cove",
    "siteCode": "CA-ACM",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 38.91503996,
    "lng": -123.71107,
    "date": "",
    "status": "",
    "season": "?",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Moat Creek",
    "siteCode": "CA-MCM",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 38.88115704,
    "lng": -123.67604,
    "date": "",
    "status": "",
    "season": "?",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Iversen Point",
    "siteCode": "CA-IPM",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 38.84875604,
    "lng": -123.64704,
    "date": "",
    "status": "",
    "season": "?",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Serenisea",
    "siteCode": "CA-SSM",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 38.797006,
    "lng": -123.57216,
    "date": "",
    "status": "",
    "season": "01/Feb/2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Del Mar",
    "siteCode": "CA-DMS",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 38.74098203,
    "lng": -123.50883,
    "date": "",
    "status": "",
    "season": "?",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Sculpture Point",
    "siteCode": "CA-SPS",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 38.70019401,
    "lng": -123.44294,
    "date": "",
    "status": "",
    "season": "31/Jan/2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Fisk Mill Cove",
    "siteCode": "CA-FMS",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 38.596819,
    "lng": -123.35041,
    "date": "",
    "status": "",
    "season": "20/Apr/2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Phillips Gulch",
    "siteCode": "CA-PGS",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 38.58643097,
    "lng": -123.34198,
    "date": "",
    "status": "",
    "season": "19/Apr/2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Windermere Point",
    "siteCode": "CA-WPS",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 38.524526,
    "lng": -123.26828,
    "date": "",
    "status": "",
    "season": "18/Apr/2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Twin Coves",
    "siteCode": "CA-TCS",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 38.45919502,
    "lng": -123.146,
    "date": "",
    "status": "",
    "season": "30/Jan/2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Bodega Head",
    "siteCode": "CA-BHS",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 38.29826701,
    "lng": -123.05671,
    "date": "",
    "status": "",
    "season": "?",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "McClures Beach",
    "siteCode": "CA-CCM",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 38.18255802,
    "lng": -122.96591,
    "date": "",
    "status": "",
    "season": "May 2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Lifeboat House",
    "siteCode": "CA-LHM",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 37.99426803,
    "lng": -122.97358,
    "date": "",
    "status": "",
    "season": "May 2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Palomarin",
    "siteCode": "CA-PMM",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 37.93013298,
    "lng": -122.74624,
    "date": "",
    "status": "",
    "season": "May 2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Duxbury Reef",
    "siteCode": "CA-DRM",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 37.89413304,
    "lng": -122.70819,
    "date": "",
    "status": "",
    "season": "21/Apr/2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Pigeon Point",
    "siteCode": "CA-PIS",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 37.18275103,
    "lng": -122.38872,
    "date": "",
    "status": "",
    "season": "July 2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Scott Creek",
    "siteCode": "CA-SCC",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 37.04420001,
    "lng": -122.23518,
    "date": "",
    "status": "",
    "season": "July 2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Cayucos",
    "siteCode": "CA-CAY",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 35.44788298,
    "lng": -120.91151,
    "date": "",
    "status": "",
    "season": "June 2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Shell Beach, SLO",
    "siteCode": "CA-SHB",
    "region": "NorCal",
    "group": "Schiebelhut Dawson",
    "lead": "Schiebelhut",
    "lat": 35.15239902,
    "lng": -120.67306,
    "date": "",
    "status": "",
    "season": "June 2026",
    "purpose": "Annual intertidal sea star surveys",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Monterey East Mooring",
    "siteCode": "ESTMOR",
    "region": "CenCal",
    "group": "Stanford SSL",
    "lead": "Shea Kidd",
    "lat": 36.60406,
    "lng": -121.8877278,
    "date": "",
    "status": "",
    "season": "Sept 2025/Anytime",
    "purpose": "Water for pycno and Vpec. eDNA.  eDNA study site",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Great Tide Pool",
    "siteCode": "GR8TPL",
    "region": "CenCal",
    "group": "SSL",
    "lead": "Kidd",
    "lat": 36.63,
    "lng": -121.94,
    "date": "",
    "status": "",
    "season": "Can be biannual?",
    "purpose": "Water for pycno and Vpec. eDNA",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Cal Poly Pier",
    "siteCode": "CPPIER",
    "region": "CenCal",
    "group": "Galaxy Quest",
    "lead": "Gravem",
    "lat": 35.172067,
    "lng": -120.737429,
    "date": "",
    "status": "",
    "season": "Can be weekly",
    "purpose": "Water for pycno and Vpec. eDNA",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Cal Poly Humboldt Trinidad Pier",
    "siteCode": "TRINPR",
    "region": "NorCal",
    "group": "UCLA SSL CPH",
    "lead": "Pacheco",
    "lat": 41.05611111111111,
    "lng": -124.14416666666668,
    "date": "",
    "status": "sampled",
    "season": "One time - hand off to CPH/TR/TD",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Luffenholtz Beach",
    "siteCode": "LUFBCH",
    "region": "NorCal",
    "group": "UCLA SSL CPH",
    "lead": "Pacheco",
    "lat": 41.040283333333335,
    "lng": -124.12096388888888,
    "date": "",
    "status": "sampled",
    "season": "One time - hand off to CPH/TR/TD",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Tankers",
    "siteCode": "TANKER",
    "region": "CenCal",
    "group": "SSL",
    "lead": "Kidd",
    "lat": null,
    "lng": null,
    "date": "",
    "status": "",
    "season": "",
    "purpose": "",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": false
  },
  {
    "name": "Scripps",
    "siteCode": "",
    "region": "",
    "group": "TNC",
    "lead": "Benkwitt Patton",
    "lat": 32.87,
    "lng": -117.26,
    "date": "",
    "status": "",
    "season": "Weekly for 1 year",
    "purpose": "Water for Vpec.",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": true
  },
  {
    "name": "UCSB",
    "siteCode": "",
    "region": "",
    "group": "TNC",
    "lead": "Benkwitt Patton",
    "lat": 34.41,
    "lng": -119.84,
    "date": "",
    "status": "",
    "season": "Weekly for 1 year",
    "purpose": "Water for Vpec.",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": true
  },
  {
    "name": "Cal Poly SLO",
    "siteCode": "",
    "region": "",
    "group": "TNC",
    "lead": "Benkwitt Patton",
    "lat": 35.18,
    "lng": -120.74,
    "date": "",
    "status": "",
    "season": "Weekly for 1 year",
    "purpose": "Water for Vpec.",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": true
  },
  {
    "name": "MLML",
    "siteCode": "",
    "region": "",
    "group": "TNC",
    "lead": "Benkwitt Patton",
    "lat": 36.8,
    "lng": -121.79,
    "date": "",
    "status": "",
    "season": "Weekly for 1 year",
    "purpose": "Water for Vpec.",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": true
  },
  {
    "name": "Bodega Marine Lab",
    "siteCode": "",
    "region": "",
    "group": "TNC",
    "lead": "Benkwitt Patton",
    "lat": 38.32,
    "lng": -123.07,
    "date": "",
    "status": "",
    "season": "Weekly for 1 year",
    "purpose": "Water for Vpec.",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": true
  },
  {
    "name": "Humboldt",
    "siteCode": "",
    "region": "",
    "group": "TNC",
    "lead": "Benkwitt Patton",
    "lat": 41.06,
    "lng": -124.15,
    "date": "",
    "status": "",
    "season": "Weekly for 1 year",
    "purpose": "Water for Vpec.",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": true
  },
  {
    "name": "Hatfield",
    "siteCode": "",
    "region": "",
    "group": "TNC",
    "lead": "Benkwitt Patton",
    "lat": 44.62,
    "lng": -124.04,
    "date": "",
    "status": "",
    "season": "Weekly for 1 year",
    "purpose": "Water for Vpec.",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": true
  },
  {
    "name": "Tillamook Estuary Partnership",
    "siteCode": "",
    "region": "",
    "group": "TNC",
    "lead": "Benkwitt Patton",
    "lat": 45.55,
    "lng": -123.92,
    "date": "",
    "status": "",
    "season": "Weekly for 1 year",
    "purpose": "Water for Vpec.",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": true
  },
  {
    "name": "Marrowstone",
    "siteCode": "",
    "region": "",
    "group": "TNC",
    "lead": "Benkwitt Patton",
    "lat": 48.1,
    "lng": -122.69,
    "date": "",
    "status": "",
    "season": "Weekly for 1 year",
    "purpose": "Water for Vpec.",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": true
  },
  {
    "name": "Friday Harbor Labs",
    "siteCode": "",
    "region": "",
    "group": "TNC",
    "lead": "Benkwitt Patton",
    "lat": 48.55,
    "lng": -123.01,
    "date": "",
    "status": "",
    "season": "Weekly for 1 year",
    "purpose": "Water for Vpec.",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": true
  },
  {
    "name": "Quadra Island",
    "siteCode": "",
    "region": "",
    "group": "TNC",
    "lead": "Benkwitt Patton",
    "lat": 50.12,
    "lng": -125.23,
    "date": "",
    "status": "",
    "season": "Weekly for 1 year",
    "purpose": "Water for Vpec.",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": true
  },
  {
    "name": "Calvert Island",
    "siteCode": "",
    "region": "",
    "group": "TNC",
    "lead": "Benkwitt Patton",
    "lat": 51.65,
    "lng": -128.13,
    "date": "",
    "status": "",
    "season": "Weekly for 1 year",
    "purpose": "Water for Vpec.",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": true
  },
  {
    "name": "University of Alaska SE",
    "siteCode": "",
    "region": "",
    "group": "TNC",
    "lead": "Benkwitt Patton",
    "lat": 58.38,
    "lng": -134.64,
    "date": "",
    "status": "",
    "season": "Weekly for 1 year",
    "purpose": "Water for Vpec.",
    "ednaBenthic": "",
    "ednaSurface": "",
    "intertidal": "",
    "collection": "",
    "storage": "",
    "notes": "",
    "vpecOnly": true
  }
];
